### ISSUE TITLE
Leaking Globals

### ISSUE THREAD

**Issue by Road-block** [Alogsdon/ZodsRaidAssign#1]
It is generally speaking good practice to avoid or at least limit global namespace writes because they lead to hard to debug interactions with other addons (or sometimes even default UI code if they shadow a variable)

If they can't be outright avoided, using variable names that at least lessen the chance of collisions.
Wrapping variables into the private addon table passed to all addon files in a vararg by the client is a good option for example.
```lua
local addonName, addon = ...
addon.myVar1 = "whatever"
addon.myVar2 = {}
addon.myFunc = function(arg1)
end
-- etc
```

Anyway to get to the point this is an interesting addon but it's leaking a ton of globals and some of them with very generic or short names.

- [i_adjust](https://github.com/Alogsdon/ZodsRaidAssign/blob/master/zra_schema.lua#L863)
- [setGetDiff](https://github.com/Alogsdon/ZodsRaidAssign/blob/master/ZodsRaidAssign.lua#L341)
- [deepCopy](https://github.com/Alogsdon/ZodsRaidAssign/blob/master/ZodsRaidAssign.lua#L477)
- [notFreshInstance](https://github.com/Alogsdon/ZodsRaidAssign/blob/master/ZodsRaidAssign.lua#L530)
- [iname](https://github.com/Alogsdon/ZodsRaidAssign/blob/master/ZodsRaidAssign.lua#L537)
- [sets](https://github.com/Alogsdon/ZodsRaidAssign/blob/master/ZodsRaidAssign.lua#L557)
- [avg](https://github.com/Alogsdon/ZodsRaidAssign/blob/master/ZodsRaidAssign.lua#L558)
- [quota](https://github.com/Alogsdon/ZodsRaidAssign/blob/master/ZodsRaidAssign.lua#L559)
- [mi](https://github.com/Alogsdon/ZodsRaidAssign/blob/master/ZodsRaidAssign.lua#L575)
- [s](https://github.com/Alogsdon/ZodsRaidAssign/blob/master/ZodsRaidAssign.lua#L615)
- [i](https://github.com/Alogsdon/ZodsRaidAssign/blob/master/ZodsRaidAssign.lua#L627)
- [mage_groups](https://github.com/Alogsdon/ZodsRaidAssign/blob/master/ZodsRaidAssign.lua#L616)
- [mage](https://github.com/Alogsdon/ZodsRaidAssign/blob/master/ZodsRaidAssign.lua#L619)
- [priest_groups](https://github.com/Alogsdon/ZodsRaidAssign/blob/master/ZodsRaidAssign.lua#L631)
- [priest](https://github.com/Alogsdon/ZodsRaidAssign/blob/master/ZodsRaidAssign.lua#L634)
- [druid_groups](https://github.com/Alogsdon/ZodsRaidAssign/blob/master/ZodsRaidAssign.lua#L646)
- [druid](https://github.com/Alogsdon/ZodsRaidAssign/blob/master/ZodsRaidAssign.lua#L649)
- All the utility function names from [ZodsRaidAssign.lua:894](https://github.com/Alogsdon/ZodsRaidAssign/blob/master/ZodsRaidAssign.lua#L894) to [ZodsRaidAssign.lua:988](https://github.com/Alogsdon/ZodsRaidAssign/blob/master/ZodsRaidAssign.lua#L988) (dump, shallowcopy, modulo, tablelen, tablefirstkey, splitmess, remaining, mysplit, dicestring, codesToValsArr)

The Lua math library does have a math.fmod method you don't need your own btw 😉 
In any case if you need utility functions available throughout your addon Lua files use the `local addonName, addon = ...` construct at the top of the files and wrap the functions into the private addon table, for example `addon.dicestring = function(str) --do my stuff end`

- [some_events](https://github.com/Alogsdon/ZodsRaidAssign/blob/master/ZodsRaidAssign.lua#L1004)
- [f](https://github.com/Alogsdon/ZodsRaidAssign/blob/master/ZRA_UI.lua#L768)

Most of those do not need some complex rewrite (I'd still wrap the utility functions in the addon private table or at least prepend the addon name to their name so they're not as generic `ZodsRaidAssign_dump` instead of `dump`.
For the rest it seems to be a case of forgetting to declare them as `local `.

Hope it helps.

**Comment by Alogsdon** [comment]
thanks a lot. I didn't expect the feedback. I'll get to refactoring.
